"""add phone number

Revision ID: 6de5e259f181
Revises: 2e1e58c1f47a
Create Date: 2026-06-27 08:30:40.252644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de5e259f181'
down_revision: Union[str, Sequence[str], None] = '2e1e58c1f47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone_number', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'phone_number')
    # ### end Alembic commands ###
